---
# tasks file for test_artifactory_repository
- name: Check link Jfrog Artifactory admin
  shell: | 
     curl -k -X GET 'http://localhost:{{ port }}/artifactory/api/repositories' \
     -u "{{ jfrog_artifactory_username }}":"{{ jfrog_artifactory_password }}" \
     -H 'content-type: application/json'
  register: output_jfrog_artifactory_repo_result
