---
# tasks file for test_port
  - name: test port
    ansible.builtin.wait_for:
       host: "localhost"
       port: "{{ port }}"
       state: started          # Port should be open
       delay: 0                # No wait before first check (sec)
       timeout: 3
    register: output_port
