---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
   - role: tests/test_port
     vars:
       port: "8046"
   - role: tests/test_artifactory_repository
     vars:
       port: "8046"
       
  tasks:

  - name: check artifactory port result 
    assert:
        that:
           - "{{ output_port.failed }} == false"    

  - name: check jfrog artifactory repositories work result 
    assert:
        that:
           - "'example-repo-local' in output_jfrog_artifactory_repo_result.stdout"  


